name: UI Tests

on:
  push:
    branches:
      - main
      - devel
      - '!temporary-docs-branch' # Ignore changes to the temporary branch
  pull_request:
    branches:
      - main
      - devel
      - '!temporary-docs-branch' # Ignore changes to the temporary branch

jobs:
  tests:
    strategy:
      matrix:
        meteor:
            - '2.14'
    name: Server Meteor ${{ matrix.meteor }} tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # CACHING
      - name: Install Meteor
        id: cache-meteor-install
        uses: actions/cache@v3
        with:
          path: ~/.meteor
          key: v2-meteor-${{ hashFiles('.meteor/versions') }}
          restore-keys: |
                v2-meteor-

      - name: Cache NPM dependencies
        id: cache-meteor-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
                v1-npm-

      - name: Cache Meteor build
        id: cache-meteor-build
        uses: actions/cache@v3
        with:
          path: |
            .meteor/local/resolver-result-cache.json
            .meteor/local/plugin-cache
            .meteor/local/isopacks
            .meteor/local/bundler-cache/scanner
          key: v2-meteor_build_cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            v2-meteor_build_cache-

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ matrix.meteor }}

      - name: Install NPM Dependencies
        run: meteor npm ci

      - name: Run Tests
        run: meteor npm run test:client
